### ISSUE TITLE
Announcement in the telegram chat

### ISSUE THREAD

**Issue by isd-crew** [fabriziosalmi/webtek#15]
Hey @fabriziosalmi,

could u announce as in the telegram chat?

Greetings d. :)

**Comment by fabriziosalmi** [comment]
Sorry I’m late here..anyway yes but we’ll introduce some automatism next time ;)

**Comment by fabriziosalmi** [comment]
@isd-crew I tested the push links feature to the telegram channel and it worked, I just need to encode it for W XIX ;)
